language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
  allow_failures:
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

script:
    - composer install
    - mkdir tests/cache
    - chmod 777 tests/cache
    - phpunit
